#!/usr/bin/env bash
# Generates the env file the codespace stack needs. Replaces the documented
# manual "cp sample.env .env and edit it" step -- a demo must need zero manual
# setup.
#
# The file is written OUTSIDE the repository, under $HOME, and never at the
# repository root. That is deliberate: a generated env file must not be able to
# reach a real MMGIS deployment. Living outside the working tree, it cannot be
# committed, cannot land in a Docker build context, and cannot be picked up by
# `npm start` or a plain `docker build` from a clone of this repo. The repo's
# .gitignore and .dockerignore both already exclude `.env`; this removes the
# need to rely on either staying correct.
#
# $HOME is also the right lifecycle: it survives a codespace stop/start exactly
# as the Postgres volume does, and is discarded on a rebuild exactly as the
# volume is, so the generated password never outlives the database it created.
#
# Runs as postCreateCommand, which Codespaces ALSO runs during a prebuild.
# Nothing secret is generated here for that reason: a secret written during a
# prebuild would be baked in and shared by every codespace made from it. SECRET
# and DB_PASS are left as placeholders and filled in at start time.
set -euo pipefail

# MMGIS_ENV_FILE is honoured only if it is an absolute path. devcontainer.json
# does not expand ${containerEnv:HOME} inside containerEnv, so setting it there
# put the literal string "${containerEnv:HOME}/..." into the environment, which
# then resolved against the working directory and created a junk directory in
# the repository. Anything not starting with / is ignored.
resolve_env_file() {
  case "${MMGIS_ENV_FILE:-}" in
    /*) printf '%s\n' "$MMGIS_ENV_FILE" ;;
    *)  printf '%s\n' "$HOME/.mmgis-codespace/.env" ;;
  esac
}

ENV_FILE="$(resolve_env_file)"

if [ -f "$ENV_FILE" ]; then
  echo "[setup-env] $ENV_FILE already exists; leaving it alone."
  exit 0
fi

mkdir -p "$(dirname "$ENV_FILE")"

# See sample.env for the full, documented set of variables. Anything left unset
# falls back to the application default.
cat > "$ENV_FILE" <<'ENV'
# Generated by .devcontainer/scripts/setup-env.sh
#
# DEMO / TESTING CREDENTIALS ONLY. Every secret below is generated for one
# codespace and is meaningless outside it. This file deliberately lives outside
# the MMGIS working tree so it can never be committed or built into an image.
# Do not copy it into a real deployment or use it as a template for one --
# sample.env is the template.
SERVER=node
PORT=8888

# Production mode on purpose. In development mode MMGIS serves the site from
# webpack-dev-server on PORT+1, and the websocket clients build their URL as
# host:PORT -- neither survives Codespaces port forwarding, where the port is
# part of the hostname rather than a :port suffix.
NODE_ENV=production

# TLS is terminated by GitHub at the forwarded-port edge; the tunnel speaks
# plain HTTP to this port. MMGIS must not try to serve HTTPS itself.
HTTPS=false

# Anyone without credentials is blocked. With an empty users table, /configure
# renders its SETUP form so the first visitor creates the admin account and
# picks their own password.
AUTH=local
AUTH_LOCAL_ALLOW_SIGNUP=false

# Filled in on first start by start.sh.
SECRET=

VERBOSE_LOGGING=false
HIDE_CONFIG=false

# Adjacent servers are off: they are not needed to show the map or Configure,
# and each one costs start-up time and memory against the visitor's quota.
WITH_STAC=false
WITH_TIPG=false
WITH_TITILER=false
WITH_TITILER_PGSTAC=false
WITH_VELOSERVER=false

# Websockets are left off for the demo. Turning them on is a good way to test
# wss through the tunnel, but it is one more thing to fail on a cold start.
ENABLE_MMGIS_WEBSOCKETS=false
ENABLE_CONFIG_WEBSOCKETS=false

# Throwaway database credentials. DB_PASS is filled in on first start and must
# then stay put: it is what initialized the Postgres volume.
DB_HOST=db
DB_PORT=5432
DB_NAME=mmgis
DB_USER=mmgis_demo
DB_PASS=GENERATED_ON_FIRST_START
DB_SSL=false
ENV

chmod 600 "$ENV_FILE"
echo "[setup-env] wrote $ENV_FILE (demo credentials only, outside the repo)"
